language: elixir
elixir:
- 1.4.0
- 1.3.0
otp_release:
- 19.0
- 18.3
sudo: false
notifications:
  email: false
  slack:
    rooms:
      secure: dZlF9tqECNhl8rGy2uQKHPSqujCwQR3AsMxDCTBCSq5b36ZY0tMS8tB+i4INY97wQEwIRtxrXhILFBKcazPK/plQqeZDg09ism8kcuM+w9h5juOTw8RNZO9tqadY/4CaQRK/6I2rsAxEST7OWOrLy+mzr6y1LvaWewJMYlYbNWMNgyXvE2ifiy96W8FSCNKMqrPVgpr8YSXUQHCQ63znWAanIWBHQt02F2nqxi412huktO/f991QtLC0GJuHKGsqbcXK+espABAIDox1EjtYP/Le611AqPBPUx/lxs71CFo8PeR++zO6xm/7FOs3MKjZr9ssr4Wn+v1M2j84DIMP08tJzJsyCtSMLpOzEGIEzD5pb8X6Pl9kpz6I1Y3KDKbyfnOeTraObKZvUboABnlBdc93NrHOBEmCiFQaXWIWU4bjRaRzwELV26P7Be8PQqn6e/vVEGuPSqCZp8GiGZnVegrUAki51kwUfQJVSSIDYYwLH1lTb950aeLMt45J8CSkUFm4pv+FYUiQWf1UVcYi7IixGAMPxHkpaHShaHqGXJHvzpD60/y0e54fYl6GlVfENxXTuAqSvHZCDLebOGBxJ4Qub5L2voaWtK6jmaAL6vlhdVJgbQl4PpugGku97ydf+aZedMahVdwmZbaIcI9cOP4+Zqb0oZAs9M9m01+8y5g=
